---
title: "doublet analysis"
output: md_document
date: '2022-08-09'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(Seurat)
library(glue)
library(scDblFinder)
library(tidyseurat)
library(tidySingleCellExperiment)
```


```{r}
## The following output is from scDblFinder

#take the output files, which include 3_prime_batch/preprocessing_output/non_batch_variation_removal
files <- dir("/stornext/Bioinf/data/bioinf-data/Papenfuss_lab/projects/roestie/roestielisa/PBMC/data/3_prime_batch_1/preprocessing_results/non_batch_variation_removal/", full.name = T)
files_annotation <- dir("/stornext/Bioinf/data/bioinf-data/Papenfuss_lab/projects/roestie/roestielisa/PBMC/data/3_prime_batch_1/preprocessing_results/annotation_label_transfer/", full.name = T)
files_doublets <- dir("/stornext/Bioinf/data/bioinf-data/Papenfuss_lab/projects/roestie/roestielisa/PBMC/data/3_prime_batch_1/preprocessing_results/doublet_identification/", full.name = T)

```


```{r}
#combine count dataframe by rows using seurat function merge
merged_combined <- 
  files |>
  map(readRDS) |>
  purrr::reduce(merge)

#have a look at the output generated by scDblFinder:
merged_combined_annotation_doublets <-
  
  #join annotation
  merged_combined |>
  left_join(
    files_annotation |>
      map(readRDS) |>
      purrr::reduce(bind_rows), by=".cell") |>
  
  #join doublets identified
  left_join(
    files_doublets |>
      map(readRDS) |>
      purrr::reduce(bind_rows), by = c(".cell"))

```


```{r, fig.width=15}
# 1a) UMAP plot, color by doublets, supervised

#plot doublets
p1 <- merged_combined_annotation_doublets |>
  ggplot(aes(refUMAP_1, refUMAP_2, color = scDblFinder.class)) +
  geom_point(shape=".")

#plot cell types
p2 <- merged_combined_annotation_doublets |>
  ggplot(aes(refUMAP_1, refUMAP_2, color = predicted.celltype.l2)) +
  geom_point(shape=".") +
  theme_bw()

p1 + p2
```


```{r, fig.width=15}
# 1b) UMAP re-clustering, to do an unsupervised visualization of the clustering of the doublets.
#selecting gene names for features
all.genes <- rownames(merged_combined_annotation_doublets)

#re-clustering
merged_combined_annotation_doublets_reclustered <-
  merged_combined_annotation_doublets |>
  RunPCA(features = all.genes) |>
  FindNeighbors(dims = 1:30) |>
  FindClusters(resolution = 0.5) |>
  RunUMAP(dims = 1:30, spread    = 0.5,min.dist  = 0.01, n.neighbors = 10L)

#plot doublets
p3 <- merged_combined_annotation_doublets_reclustered |>
  ggplot(aes(UMAP_1, UMAP_2, color = scDblFinder.class)) +
  geom_point(shape=".") +
  guides(color = guide_legend(override.aes = list(size = 5))) +
  theme_bw()

#plot cell types
p4 <- merged_combined_annotation_doublets_reclustered |>
  ggplot(aes(UMAP_1, UMAP_2, color = predicted.celltype.l2)) +
  geom_point(shape=".") +
  guides(color = guide_legend(override.aes = list(size = 5))) +
  theme_bw()

p3 + p4
```


```{r, fig.width=15}
# 2) Create the composition of the doublets

merged_combined_annotation_doublets %>% select(sample, scDblFinder.class) %>% table()

#calculate proportion and plot
plot_composition_proportion_faceted <-
  merged_combined_annotation_doublets |>
  select(sample, nCount_SCT, predicted.celltype.l2, scDblFinder.class) |>
  
  # create frquency column
  mutate(frequency = nCount_SCT/sum(nCount_SCT)*100) |>
  
  # create the proportion column
  group_by(sample) |>
  mutate(tot_sample_proportion = sum(frequency)) |>
  ungroup() |>
  mutate(proportion = (frequency * 1)/tot_sample_proportion) |>
  
  #plot proportion
  ggplot(aes(x = sample, y = proportion, fill = predicted.celltype.l2)) +
  geom_bar(stat = "identity") +
  theme_bw() +
  facet_wrap(~scDblFinder.class) +
  theme(axis.text.x=element_text(angle=70, hjust=1))

#visualise
plot_composition_proportion_faceted

```

